PREFIX=/usr/local/bin

all:
	ocp-build -asm ocp-edit-mode ocp-spotter ocp-fix-errors

install:
	cp ../../_obuild/ocp-edit-mode/ocp-edit-mode.asm $(PREFIX)/ocp-edit-mode
	cp ../../_obuild/ocp-fix-errors/ocp-fix-errors.asm $(PREFIX)/ocp-fix-errors
	cp ../../_obuild/ocp-spotter/ocp-spotter.asm $(PREFIX)/ocp-spotter
